### ISSUE TITLE
Verify working characterization

### ISSUE THREAD

**Issue by afred** [WGBH/hydradam2#34]
**Done when** a uploaded video file gets properly characterized.

**Comment by Muraszko** [comment]
@afred Is this just a test to cover features for other people who may use HD2 besides IU and WGBH?

**Comment by afred** [comment]
Not exactly. There is already a spot for FITS in CurationConcerns, but it gets populated via the characterization process. We may end up using the spot, but bypassing the process. I just want to make sure it's currently working as advertised before I try to tweak it.

**Comment by afred** [comment]
Verified.. however the raw FITS xml is not being stored. Rather it is being extracted, and parsed, but only temporarily. After the values are assigned to RDF properties, the XML is discarded. This isn't what we want, so creating #36. Closing this one.
