### ISSUE TITLE
Question: should FileSet objects be included in search results?

### ISSUE THREAD

**Issue by afred** [WGBH/hydradam2#44]
**Background:** The CurationConcerns default is to allow discovery of Works and Collections. The individual FileSet objects contained within each Work do not show up in search results.

We want items to be discoverable by technical metadata (and possibly by content from other files attached to a work).

I see two ways to do this:
  1. Either add metadata from attached file to the Solr documents of Works (and Collections?)
    - this could make Solr documents for some Works extremely large
    - very large Solr documents with lots of searchable content also leads to unintuitive search results.
  1. Tweak the search behavior to return FileSet objects as part of the search restults.
    - they are already being stored in Solr. So I like this solution better.

**Comment by afred** [comment]
See #45

**Comment by Muraszko** [comment]
@afred So if you wanted to search by a given file's MD5 value.  As it's set up now, what would the search results page look like?

**Comment by afred** [comment]
@Muraszko right now, it wouldn't return anything. Technical md is not part of search behavior, so even if you enter a valid MD5 for a file attached to a Work, then neither the file, nor the Work would not show up.

What would you expect the results to be?
  1. just the file with the MD5
  2. just the Work containing the file with the MD5
  3. both the file with the MD5, and the Work containing the file
  4. other?

**Comment by Muraszko** [comment]
I guess I would just expect the search results page to be 2.  Thinking about IU's use cases, they need their work to contain the contents of the SIP package, which are all within the Work, right?

**Comment by afred** [comment]
I assume so, but not sure.

**Comment by afred** [comment]
@Muraszko the issue I see with option (2) is conflated search results. For instance, if a Work (which may be a Program for us) contains 50 files, then the 50 different searches on those MD5 hashes would all result in the same, single, search result. Is that what we want?

Note that if a Work (i.e. Program) shows up in the search results, you can click it and see all the files. And likewise, if a File shows up in the search results, you should be able to click it and see what Program it belongs to.

Perhaps a good exercise would be to get the top 3 (or more?) use cases for search, by filling in the following sentence:
"I need to be able to find [X] when all I have to search by is [Y]"

I went ahead and made some tweaks that allow FileSet objects to be returned in search results, more as a feasibility exercise than anything. It can be easily undone, I want to show it to you first.

**Comment by Muraszko** [comment]
@afred Thanks for explaining that, 2 would be a problem in that case.
I'll send along some use cases for potential searches.

**Comment by afred** [comment]
@Muraszko can you confirm that my interpretation of your search use cases are correct in this gist? https://gist.github.com/afred/a530c353b61df8cc01db

**Comment by Muraszko** [comment]
@afred Looks good.  Thanks.

**Comment by afred** [comment]
**Answer** yes, for now we're including FileSets (labeled as just "Files") in the general search results.
