### ISSUE TITLE
Disallow re-saving of "similar" objects during WGBH ingest

### ISSUE THREAD

**Issue by afred** [WGBH/hydradam2#84]
**Done when**
  * we have defined what 'similar' means for a WGBH item
  * the WGBH ingester does not ingest similar items more than once

**Comment by afred** [comment]
@Muraszko is it sufficient to use the checksum contained within FITS, EXIF, or PBCore metadata to determine whether an item exists in HydraDAM?

Also, is it true that we _don't_ want to ingest items twice?

**Comment by Muraszko** [comment]
Just discussed in person.  We're going to explore using LTO barcode and file path to determine if an item exists already.

Also, trying to determine if some kind of Bag-It system would work better for ingest of the FITS files to provide the basic descriptive metadata not found in the technical xml we're ingesting.
